[project]
name = "edgar"
version = "0.1.0"
description = "A small client to fetch 10-K reports from the SEC EDGAR API"
readme = "README.md"
authors = [
    { name = "Paolo Dragone", email = "dragone.paolo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pyrate-limiter>=4.1.0",
    "weasyprint>=68.1",
]

[project.scripts]
sec-edgar = "edgar:main"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.12.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-httpx>=0.36.2",
    "pytest-mock>=3.15.1",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = [
    "--import-mode=importlib",
]
